// generated by unplugin-vue-components
// We suggest you to commit this file into source control
// Read more: https://github.com/vuejs/vue-next/pull/3399

declare module 'vue' {
  export interface GlobalComponents {
    AAvatar: typeof import('ant-design-vue/es')['Avatar']
    AButton: typeof import('ant-design-vue/es')['Button']
    AForm: typeof import('ant-design-vue/es')['Form']
    AFormItem: typeof import('ant-design-vue/es')['FormItem']
    AInput: typeof import('ant-design-vue/es')['Input']
    AInputPassword: typeof import('ant-design-vue/es')['InputPassword']
    AList: typeof import('ant-design-vue/es')['List']
    AListItem: typeof import('ant-design-vue/es')['ListItem']
    AListItemMeta: typeof import('ant-design-vue/es')['ListItemMeta']
    ASkeleton: typeof import('ant-design-vue/es')['Skeleton']
    ATextarea: typeof import('ant-design-vue/es')['Textarea']
    Icon: typeof import('./src/components/Icon.vue')['default']
    NodeList: typeof import('./src/components/NodeList.vue')['default']
    PreviewNode: typeof import('./src/components/PreviewNode.vue')['default']
  }
}

export {}
